apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "identity-service.fullname" . }}
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/identity
        pathType: Prefix
        backend:
          service:
            name: {{ include "identity-service.fullname" . }}
            port:
              number: {{ .Values.service.port }}
