apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/cart
        pathType: Prefix
        backend:
          service:
            name: cart-service
            port:
              number: {{ .Values.service.port }}
