// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: loyalty/v1/loyalty.proto

package loyaltyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoyaltyService_GetLoyaltyBalance_FullMethodName   = "/loyalty.v1.LoyaltyService/GetLoyaltyBalance"
	LoyaltyService_DeductLoyaltyPoints_FullMethodName = "/loyalty.v1.LoyaltyService/DeductLoyaltyPoints"
	LoyaltyService_RefundLoyaltyPoints_FullMethodName = "/loyalty.v1.LoyaltyService/RefundLoyaltyPoints"
	LoyaltyService_AddLoyaltyPoints_FullMethodName    = "/loyalty.v1.LoyaltyService/AddLoyaltyPoints"
)

// LoyaltyServiceClient is the client API for LoyaltyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoyaltyServiceClient interface {
	GetLoyaltyBalance(ctx context.Context, in *GetLoyaltyBalanceRequest, opts ...grpc.CallOption) (*GetLoyaltyBalanceResponse, error)
	DeductLoyaltyPoints(ctx context.Context, in *DeductLoyaltyPointsRequest, opts ...grpc.CallOption) (*DeductLoyaltyPointsResponse, error)
	RefundLoyaltyPoints(ctx context.Context, in *RefundLoyaltyPointsRequest, opts ...grpc.CallOption) (*RefundLoyaltyPointsResponse, error)
	AddLoyaltyPoints(ctx context.Context, in *AddLoyaltyPointsRequest, opts ...grpc.CallOption) (*AddLoyaltyPointsResponse, error)
}

type loyaltyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoyaltyServiceClient(cc grpc.ClientConnInterface) LoyaltyServiceClient {
	return &loyaltyServiceClient{cc}
}

func (c *loyaltyServiceClient) GetLoyaltyBalance(ctx context.Context, in *GetLoyaltyBalanceRequest, opts ...grpc.CallOption) (*GetLoyaltyBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoyaltyBalanceResponse)
	err := c.cc.Invoke(ctx, LoyaltyService_GetLoyaltyBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loyaltyServiceClient) DeductLoyaltyPoints(ctx context.Context, in *DeductLoyaltyPointsRequest, opts ...grpc.CallOption) (*DeductLoyaltyPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductLoyaltyPointsResponse)
	err := c.cc.Invoke(ctx, LoyaltyService_DeductLoyaltyPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loyaltyServiceClient) RefundLoyaltyPoints(ctx context.Context, in *RefundLoyaltyPointsRequest, opts ...grpc.CallOption) (*RefundLoyaltyPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundLoyaltyPointsResponse)
	err := c.cc.Invoke(ctx, LoyaltyService_RefundLoyaltyPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loyaltyServiceClient) AddLoyaltyPoints(ctx context.Context, in *AddLoyaltyPointsRequest, opts ...grpc.CallOption) (*AddLoyaltyPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLoyaltyPointsResponse)
	err := c.cc.Invoke(ctx, LoyaltyService_AddLoyaltyPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoyaltyServiceServer is the server API for LoyaltyService service.
// All implementations must embed UnimplementedLoyaltyServiceServer
// for forward compatibility.
type LoyaltyServiceServer interface {
	GetLoyaltyBalance(context.Context, *GetLoyaltyBalanceRequest) (*GetLoyaltyBalanceResponse, error)
	DeductLoyaltyPoints(context.Context, *DeductLoyaltyPointsRequest) (*DeductLoyaltyPointsResponse, error)
	RefundLoyaltyPoints(context.Context, *RefundLoyaltyPointsRequest) (*RefundLoyaltyPointsResponse, error)
	AddLoyaltyPoints(context.Context, *AddLoyaltyPointsRequest) (*AddLoyaltyPointsResponse, error)
	mustEmbedUnimplementedLoyaltyServiceServer()
}

// UnimplementedLoyaltyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoyaltyServiceServer struct{}

func (UnimplementedLoyaltyServiceServer) GetLoyaltyBalance(context.Context, *GetLoyaltyBalanceRequest) (*GetLoyaltyBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoyaltyBalance not implemented")
}
func (UnimplementedLoyaltyServiceServer) DeductLoyaltyPoints(context.Context, *DeductLoyaltyPointsRequest) (*DeductLoyaltyPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductLoyaltyPoints not implemented")
}
func (UnimplementedLoyaltyServiceServer) RefundLoyaltyPoints(context.Context, *RefundLoyaltyPointsRequest) (*RefundLoyaltyPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundLoyaltyPoints not implemented")
}
func (UnimplementedLoyaltyServiceServer) AddLoyaltyPoints(context.Context, *AddLoyaltyPointsRequest) (*AddLoyaltyPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLoyaltyPoints not implemented")
}
func (UnimplementedLoyaltyServiceServer) mustEmbedUnimplementedLoyaltyServiceServer() {}
func (UnimplementedLoyaltyServiceServer) testEmbeddedByValue()                        {}

// UnsafeLoyaltyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoyaltyServiceServer will
// result in compilation errors.
type UnsafeLoyaltyServiceServer interface {
	mustEmbedUnimplementedLoyaltyServiceServer()
}

func RegisterLoyaltyServiceServer(s grpc.ServiceRegistrar, srv LoyaltyServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoyaltyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoyaltyService_ServiceDesc, srv)
}

func _LoyaltyService_GetLoyaltyBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoyaltyBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoyaltyServiceServer).GetLoyaltyBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoyaltyService_GetLoyaltyBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoyaltyServiceServer).GetLoyaltyBalance(ctx, req.(*GetLoyaltyBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoyaltyService_DeductLoyaltyPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductLoyaltyPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoyaltyServiceServer).DeductLoyaltyPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoyaltyService_DeductLoyaltyPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoyaltyServiceServer).DeductLoyaltyPoints(ctx, req.(*DeductLoyaltyPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoyaltyService_RefundLoyaltyPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundLoyaltyPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoyaltyServiceServer).RefundLoyaltyPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoyaltyService_RefundLoyaltyPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoyaltyServiceServer).RefundLoyaltyPoints(ctx, req.(*RefundLoyaltyPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoyaltyService_AddLoyaltyPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLoyaltyPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoyaltyServiceServer).AddLoyaltyPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoyaltyService_AddLoyaltyPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoyaltyServiceServer).AddLoyaltyPoints(ctx, req.(*AddLoyaltyPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoyaltyService_ServiceDesc is the grpc.ServiceDesc for LoyaltyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoyaltyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loyalty.v1.LoyaltyService",
	HandlerType: (*LoyaltyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLoyaltyBalance",
			Handler:    _LoyaltyService_GetLoyaltyBalance_Handler,
		},
		{
			MethodName: "DeductLoyaltyPoints",
			Handler:    _LoyaltyService_DeductLoyaltyPoints_Handler,
		},
		{
			MethodName: "RefundLoyaltyPoints",
			Handler:    _LoyaltyService_RefundLoyaltyPoints_Handler,
		},
		{
			MethodName: "AddLoyaltyPoints",
			Handler:    _LoyaltyService_AddLoyaltyPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loyalty/v1/loyalty.proto",
}
