apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-service
  labels:
    app: pdf-service
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/pdf
        pathType: Prefix
        backend:
          service:
            name: pdf-service
            port:
              number: {{ .Values.service.port }}
