kong:

postgresql:
  image:
    tag: latest
    pullPolicy: IfNotPresent
  auth:
    database: micro_service_db
    username: admin
    existingSecret: "db-credentials"
    secretKeys:
      adminPasswordKey: "POSTGRES_ADMIN_PASSWORD"
      userPasswordKey: "DB_PASSWORD"
  persistence:
    enabled: true
    size: 1Gi
  primary:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    initdb:
      scripts:
        create-databases.sql: |
          CREATE DATABASE order_db;
          GRANT ALL PRIVILEGES ON DATABASE order_db TO admin;
          CREATE DATABASE inventory_db;
          GRANT ALL PRIVILEGES ON DATABASE inventory_db TO admin;


mongodb:
  image:
    tag: latest
    pullPolicy: IfNotPresent
  auth:
    rootUser: root
    database: payments_db
    usernames: ["admin"]
    databases: ["payments_db"]
    existingSecret: "db-credentials"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
